// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: realtime/internals/Gprc/Notification.proto

package Notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationParam struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// 3. Changed 'int' to 'int32' (or int64)
	// 4. Added missing semicolons
	Ids           []int32 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationParam) Reset() {
	*x = NotificationParam{}
	mi := &file_realtime_internals_Gprc_Notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationParam) ProtoMessage() {}

func (x *NotificationParam) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_internals_Gprc_Notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationParam.ProtoReflect.Descriptor instead.
func (*NotificationParam) Descriptor() ([]byte, []int) {
	return file_realtime_internals_Gprc_Notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationParam) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationParam) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type NotificationReturn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecievedIds    []int32                `protobuf:"varint,1,rep,packed,name=recieved_ids,json=recievedIds,proto3" json:"recieved_ids,omitempty"`
	NotRecievedIds []int32                `protobuf:"varint,2,rep,packed,name=not_recieved_ids,json=notRecievedIds,proto3" json:"not_recieved_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationReturn) Reset() {
	*x = NotificationReturn{}
	mi := &file_realtime_internals_Gprc_Notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationReturn) ProtoMessage() {}

func (x *NotificationReturn) ProtoReflect() protoreflect.Message {
	mi := &file_realtime_internals_Gprc_Notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationReturn.ProtoReflect.Descriptor instead.
func (*NotificationReturn) Descriptor() ([]byte, []int) {
	return file_realtime_internals_Gprc_Notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationReturn) GetRecievedIds() []int32 {
	if x != nil {
		return x.RecievedIds
	}
	return nil
}

func (x *NotificationReturn) GetNotRecievedIds() []int32 {
	if x != nil {
		return x.NotRecievedIds
	}
	return nil
}

var File_realtime_internals_Gprc_Notification_proto protoreflect.FileDescriptor

const file_realtime_internals_Gprc_Notification_proto_rawDesc = "" +
	"\n" +
	"*realtime/internals/Gprc/Notification.proto\x12\fNotification\"?\n" +
	"\x11NotificationParam\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x05R\x03ids\"a\n" +
	"\x12NotificationReturn\x12!\n" +
	"\frecieved_ids\x18\x01 \x03(\x05R\vrecievedIds\x12(\n" +
	"\x10not_recieved_ids\x18\x02 \x03(\x05R\x0enotRecievedIds2c\n" +
	"\x13NotificationService\x12L\n" +
	"\aNotifiy\x12\x1f.Notification.NotificationParam\x1a .Notification.NotificationReturnB*Z(go-dashboard/internals/Gprc/Notificationb\x06proto3"

var (
	file_realtime_internals_Gprc_Notification_proto_rawDescOnce sync.Once
	file_realtime_internals_Gprc_Notification_proto_rawDescData []byte
)

func file_realtime_internals_Gprc_Notification_proto_rawDescGZIP() []byte {
	file_realtime_internals_Gprc_Notification_proto_rawDescOnce.Do(func() {
		file_realtime_internals_Gprc_Notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtime_internals_Gprc_Notification_proto_rawDesc), len(file_realtime_internals_Gprc_Notification_proto_rawDesc)))
	})
	return file_realtime_internals_Gprc_Notification_proto_rawDescData
}

var file_realtime_internals_Gprc_Notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_realtime_internals_Gprc_Notification_proto_goTypes = []any{
	(*NotificationParam)(nil),  // 0: Notification.NotificationParam
	(*NotificationReturn)(nil), // 1: Notification.NotificationReturn
}
var file_realtime_internals_Gprc_Notification_proto_depIdxs = []int32{
	0, // 0: Notification.NotificationService.Notifiy:input_type -> Notification.NotificationParam
	1, // 1: Notification.NotificationService.Notifiy:output_type -> Notification.NotificationReturn
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_realtime_internals_Gprc_Notification_proto_init() }
func file_realtime_internals_Gprc_Notification_proto_init() {
	if File_realtime_internals_Gprc_Notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtime_internals_Gprc_Notification_proto_rawDesc), len(file_realtime_internals_Gprc_Notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtime_internals_Gprc_Notification_proto_goTypes,
		DependencyIndexes: file_realtime_internals_Gprc_Notification_proto_depIdxs,
		MessageInfos:      file_realtime_internals_Gprc_Notification_proto_msgTypes,
	}.Build()
	File_realtime_internals_Gprc_Notification_proto = out.File
	file_realtime_internals_Gprc_Notification_proto_goTypes = nil
	file_realtime_internals_Gprc_Notification_proto_depIdxs = nil
}
