export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-fixed-dim": "#7bd0ff",
              "on-secondary-container": "#00374d",
              "primary": "#4edea3",
              "surface-variant": "#2d3449",
              "secondary-fixed": "#c4e7ff",
              "inverse-primary": "#006c49",
              "tertiary-container": "#e29100",
              "surface-container-low": "#131b2e",
              "surface-container-lowest": "#060e20",
              "tertiary": "#ffb95f",
              "on-tertiary-fixed": "#2a1700",
              "on-error": "#690005",
              "on-surface": "#dae2fd",
              "on-secondary": "#00354a",
              "surface-container": "#171f33",
              "surface-bright": "#31394d",
              "tertiary-fixed": "#ffddb8",
              "error-container": "#93000a",
              "on-background": "#dae2fd",
              "secondary": "#7bd0ff",
              "on-tertiary-fixed-variant": "#653e00",
              "on-tertiary-container": "#523200",
              "on-secondary-fixed": "#001e2c",
              "surface-tint": "#4edea3",
              "on-error-container": "#ffdad6",
              "surface-dim": "#0b1326",
              "surface": "#0b1326",
              "surface-container-high": "#222a3d",
              "on-primary-fixed": "#002113",
              "on-secondary-fixed-variant": "#004c69",
              "on-primary": "#003824",
              "outline-variant": "#3c4a42",
              "on-primary-container": "#00422b",
              "inverse-on-surface": "#283044",
              "primary-fixed": "#6ffbbe",
              "inverse-surface": "#dae2fd",
              "outline": "#86948a",
              "on-surface-variant": "#bbcabf",
              "secondary-container": "#00a6e0",
              "primary-container": "#10b981",
              "error": "#ffb4ab",
              "primary-fixed-dim": "#4edea3",
              "background": "#0b1326",
              "on-primary-fixed-variant": "#005236",
              "tertiary-fixed-dim": "#ffb95f",
              "on-tertiary": "#472a00",
              "surface-container-highest": "#2d3449"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "xl": "40px",
              "margin-mobile": "16px",
              "gutter": "16px",
              "md": "16px",
              "base": "4px",
              "lg": "24px",
              "xs": "4px",
              "margin-desktop": "32px",
              "sm": "8px"
      },
      "fontFamily": {
              "data-lg": ["JetBrains Mono", "monospace"],
              "label-caps": ["JetBrains Mono", "monospace"],
              "title-sm": ["Inter", "sans-serif"],
              "display-lg": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "data-md": ["JetBrains Mono", "monospace"],
              "headline-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "data-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
              "title-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
              "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "data-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-md-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "label-caps-mobile": ["10px", {"lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
